# Generated by Django 2.1.7 on 2019-02-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catfact',
            old_name='author',
            new_name='api_id',
        ),
    ]
